name = "SimpleDiffEq"
uuid = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
version = "1.12.0"
repo = "https://github.com/SciML/SimpleDiffEq.jl.git"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DiffEqBase = "6.122"
ExplicitImports = "1.14.0"
JLArrays = "0.1, 0.2, 0.3"
MuladdMacro = "0.2"
OrdinaryDiffEq = "6"
Parameters = "0.12"
RecursiveArrayTools = "2, 3"
Reexport = "0.2, 1.0"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
julia = "1.6"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "JLArrays", "OrdinaryDiffEq", "SafeTestsets", "Test"]
