name = "SimpleDiffEq"
uuid = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
repo = "https://github.com/JuliaDiffEq/SimpleDiffEq.jl.git"
version = "1.3.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DiffEqBase = "6.11"
MuladdMacro = "0.2"
RecursiveArrayTools = "2"
Reexport = "0.2"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "OrdinaryDiffEq", "Test"]
